In [11]:
import numpy as np
import cv2
import pandas as pd

In [21]:
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\bohem.14.jpg')
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\bohem.14.jpg',1)
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mix\bohem.14.jpg',cv2.IMREAD_COLOR)
img1 = cv2.resize(img1,(504,378))

print(type(img1))

print(np.shape(img1))

print(img1)

cv2.imshow("image1",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
(378, 504, 3)
[[[220 218 217]
  [221 219 218]
  [217 215 214]
  ...
  [ 57  61  49]
  [ 65  68  56]
  [ 51  57  40]]

 [[221 219 218]
  [220 218 217]
  [218 216 215]
  ...
  [ 58  60  48]
  [ 59  62  50]
  [ 55  60  45]]

 [[219 217 216]
  [219 217 216]
  [215 213 212]
  ...
  [ 62  64  52]
  [ 66  68  56]
  [ 49  54  39]]

 ...

 [[ 21  28  21]
  [ 21  28  21]
  [ 25  32  25]
  ...
  [ 25  29  23]
  [ 28  32  27]
  [ 32  36  31]]

 [[ 24  29  21]
  [ 15  19  12]
  [ 21  28  20]
  ...
  [ 32  36  31]
  [ 31  35  29]
  [ 38  42  36]]

 [[ 19  24  16]
  [ 24  29  21]
  [ 14  22  13]
  ...
  [ 28  32  27]
  [ 28  32  27]
  [ 29  33  28]]]


In [13]:
img1_grey = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mix\bohem.14.jpg',cv2.IMREAD_GRAYSCALE)
img1_grey = cv2.resize(img1_grey,(504,378))

cv2.imshow("image1_grey",img1_grey)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
print(type(img1_grey))
print(img1_grey)
np.savetxt('ttest.csv',img1_grey,delimiter=",")

<class 'numpy.ndarray'>
[[218 219 215 ...  57  64  51]
 [219 218 216 ...  56  58  55]
 [217 217 213 ...  60  64  49]
 ...
 [ 25  25  29 ...  27  30  34]
 [ 26  17  25 ...  34  33  40]
 [ 21  26  18 ...  30  30  31]]


In [15]:
df = pd.DataFrame(img1_grey)

df.to_csv('tttest.csv', index=False)

In [16]:
canny_img1 = cv2.Canny(img1_grey, 100,255)

cv2.imshow("canny",canny_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
sobel_img1 = cv2.Sobel(img1_grey, cv2.CV_8U, 1, 0, 3)

cv2.imshow("sobel", sobel_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
laplacian_img1 = cv2.Laplacian(img1_grey, cv2.CV_8U, ksize=3)

cv2.imshow("laplacian", laplacian_img1)
cv2.waitKey()
cv2.destroyAllWindows()