In [1]:
import cv2
import numpy as np
import pandas as pd
import os
from sklearn import utils
from tqdm.notebook import tqdm

In [2]:
train_dir = r'C:\Users\Iver_Home\CP_ft\mix_test'

In [3]:
def labeling(img):
    class_name = img.split('.')[0]
    if class_name == 'mevius':
        return 1
    elif class_name =='marlboro':
        return 2
    elif class_name =='esse':
        return 3
    elif class_name =='bohem':
        return 4
    elif class_name =='dunhill':
        return 5
    

In [4]:
print(labeling('esse.14.jpg'))

3


In [5]:
x_data = list()
t_data = list()

In [6]:
print(os.listdir(train_dir))
arr127 = np.full((252,189),127)



['bohem.1.jpg', 'bohem.2.jpg', 'bohem.3.jpg', 'dunhill.1.jpg', 'dunhill.2.jpg', 'dunhill.3.jpg', 'esse.1.jpg', 'esse.2.jpg', 'esse.3.jpg', 'marlboro.1.jpg', 'marlboro.2.jpg', 'marlboro.3.jpg', 'mevius.1.jpg', 'mevius.2.jpg', 'mevius.3.jpg']


In [7]:

for img in tqdm(os.listdir(train_dir)):
    total = len(os.listdir(train_dir))   #=100
    position = 0
    leave = True
    label_data = labeling(img)
    img_path = os.path.join(train_dir,img)
    img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_GRAYSCALE),(189,252))
    #img_data : 2d array
    img_data = img_data + arr127
    x_data.append(img_data.ravel())
    t_data.append(label_data)
print(img_data)

  0%|          | 0/15 [00:00<?, ?it/s]

[[169 171 172 ... 168 166 165]
 [175 163 164 ... 169 166 163]
 [167 174 166 ... 171 164 165]
 ...
 [166 166 167 ... 153 154 154]
 [162 165 162 ... 154 154 154]
 [163 171 163 ... 159 160 163]]


In [8]:
x_df = pd.DataFrame(x_data)
t_df = pd.DataFrame({'label':t_data})
display(x_df)

0      1      2      3      4      5      6      7      8      9      ...  \
0     190    178    189    179    181    254    273    244    177    165  ...   
1     168    166    165    166    163    209    262    259    255    250  ...   
2     173    173    176    179    174    171    173    174    180    177  ...   
3     206    211    217    215    215    213    210    205    201    196  ...   
4     198    204    207    200    185    190    187    191    191    190  ...   
5     186    180    185    189    189    190    194    194    197    200  ...   
6     185    169    181    186    178    170    176    180    181    179  ...   
7     207    209    219    216    227    220    224    221    221    221  ...   
8     324    244    185    168    172    171    172    171    178    191  ...   
9     161    162    157    161    164    168    168    175    178    174  ...   
10    161    160    162    166    162    151    158    156    160    156  ...   
11    159    165    164    164    158    166    167    174    169    164  ...   
12    162    159    160    156    159    163    167    168    173    167  ...   
13    163    164    163    160    172    162    166    159    161    163  ...   
14    169    171    172    176    167    159    167    161    164    168  ...   

    47618  47619  47620  47621  47622  47623  47624  47625  47626  47627  
0     159    161    159    158    159    166    164    167    166    167  
1     161    159    160    158    162    165    168    166    168    164  
2     177    173    178    171    176    173    171    179    183    179  
3     176    177    183    186    174    199    185    183    183    178  
4     200    200    204    202    207    203    208    202    210    209  
5     179    185    182    181    183    180    176    190    187    181  
6     169    171    159    165    167    166    174    179    181    179  
7     164    165    164    162    167    171    164    169    171    171  
8     163    164    165    171    157    164    164    163    163    163  
9     158    156    151    159    161    160    156    159    164    155  
10    165    152    156    160    158    157    157    160    163    158  
11    157    156    146    157    155    150    155    153    159    161  
12    172    162    169    175    170    168    167    174    177    171  
13    145    147    150    148    152    155    148    152    154    150  
14    151    149    153    153    150    158    145    159    160    163  

[15 rows x 47628 columns]

In [9]:
df = pd.merge(t_df, x_df, left_index=True, right_index=True)
display(x_df)

0      1      2      3      4      5      6      7      8      9      ...  \
0     190    178    189    179    181    254    273    244    177    165  ...   
1     168    166    165    166    163    209    262    259    255    250  ...   
2     173    173    176    179    174    171    173    174    180    177  ...   
3     206    211    217    215    215    213    210    205    201    196  ...   
4     198    204    207    200    185    190    187    191    191    190  ...   
5     186    180    185    189    189    190    194    194    197    200  ...   
6     185    169    181    186    178    170    176    180    181    179  ...   
7     207    209    219    216    227    220    224    221    221    221  ...   
8     324    244    185    168    172    171    172    171    178    191  ...   
9     161    162    157    161    164    168    168    175    178    174  ...   
10    161    160    162    166    162    151    158    156    160    156  ...   
11    159    165    164    164    158    166    167    174    169    164  ...   
12    162    159    160    156    159    163    167    168    173    167  ...   
13    163    164    163    160    172    162    166    159    161    163  ...   
14    169    171    172    176    167    159    167    161    164    168  ...   

    47618  47619  47620  47621  47622  47623  47624  47625  47626  47627  
0     159    161    159    158    159    166    164    167    166    167  
1     161    159    160    158    162    165    168    166    168    164  
2     177    173    178    171    176    173    171    179    183    179  
3     176    177    183    186    174    199    185    183    183    178  
4     200    200    204    202    207    203    208    202    210    209  
5     179    185    182    181    183    180    176    190    187    181  
6     169    171    159    165    167    166    174    179    181    179  
7     164    165    164    162    167    171    164    169    171    171  
8     163    164    165    171    157    164    164    163    163    163  
9     158    156    151    159    161    160    156    159    164    155  
10    165    152    156    160    158    157    157    160    163    158  
11    157    156    146    157    155    150    155    153    159    161  
12    172    162    169    175    170    168    167    174    177    171  
13    145    147    150    148    152    155    148    152    154    150  
14    151    149    153    153    150    158    145    159    160    163  

[15 rows x 47628 columns]

In [10]:
shuffled_df = utils.shuffle(df)

In [11]:
shuffled_df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test_15.csv', index=False)
#df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test_all2.csv', index=False)