In [1]:
import cv2
import numpy as np
import pandas as pd
import os
from sklearn import utils
from tqdm.notebook import tqdm

In [2]:
train_dir = r'C:\Users\Iver_Home\CP_ft\temp'

In [3]:
def labeling(img):
    class_name = img.split('.')[0]
    if class_name == 'mevius':
        return 1
    elif class_name =='marlboro':
        return 2
    elif class_name =='esse':
        return 3
    elif class_name =='bohem':
        return 4
    elif class_name =='dunhill':
        return 5
    

In [4]:
print(labeling('esse.14.jpg'))

3


In [5]:
x_data = list()
t_data = list()

In [6]:
print(os.listdir(train_dir))

for img in tqdm(os.listdir(train_dir)):
    total = len(os.listdir(train_dir))   #=100
    label_data = labeling(img)
    img_path = os.path.join(train_dir,img)
    img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_GRAYSCALE),(189,252))
    #img_data : 2d array
    x_data.append(img_data.ravel())
    t_data.append(label_data)
print(img_data)
    


['bohem.14.jpg']


  0%|          | 0/1 [00:00<?, ?it/s]

[[220 213 204 ...  55  55  50]
 [214 209 176 ...  59  54  54]
 [210 196 152 ...  58  63  62]
 ...
 [ 15  32  35 ...  33  36  28]
 [ 29  37  39 ...  32  34  32]
 [ 28  29  41 ...  36  35  33]]


In [ ]:
x_df = pd.DataFrame(x_data)
t_df = pd.DataFrame({'label':t_data})
display(x_df)

In [ ]:
df = pd.merge(t_df, x_df, left_index=True, right_index=True)
display(x_df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
#shuffled_df = utils.shuffle(df)

In [ ]:
#shuffled_df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test.csv', index=False)
df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test3.csv', index=False)