In [10]:
import numpy as np
import cv2
import pandas as pd

In [13]:
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\mevius.1.jpg')
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\mevius.1.jpg',1)
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\mevius.1.jpg',cv2.IMREAD_REDUCED_COLOR_2)
img1 = cv2.resize(img1,(126,95))

print(type(img1))

cv2.imshow("image1",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>


In [3]:
img1_grey = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\mevius.1.jpg',cv2.IMREAD_GRAYSCALE)
img1_grey = cv2.resize(img1_grey,(126,95))

cv2.imshow("image1_grey",img1_grey)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
print(type(img1_grey))
print(img1_grey)
np.savetxt('ttest.csv',img1_grey,delimiter=",")

<class 'numpy.ndarray'>
[[32 52 39 ... 40 41 37]
 [45 41 35 ... 38 36 35]
 [38 37 35 ... 45 37 42]
 ...
 [45 40 45 ... 31 28 30]
 [37 41 43 ... 31 32 31]
 [40 47 39 ... 31 29 27]]


In [5]:
df = pd.DataFrame(img1_grey)

df.to_csv('tttest.csv', index=False)

In [6]:
canny_img1 = cv2.Canny(img1_grey, 100,255)

cv2.imshow("canny",canny_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
sobel_img1 = cv2.Sobel(img1_grey, cv2.CV_8U, 1, 0, 3)

cv2.imshow("sobel", sobel_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
laplacian_img1 = cv2.Laplacian(img1_grey, cv2.CV_8U, ksize=3)

cv2.imshow("laplacian", laplacian_img1)
cv2.waitKey()
cv2.destroyAllWindows()