In [83]:
import cv2
import numpy as np
import pandas as pd
import os
from sklearn import utils
from tqdm.notebook import tqdm

In [84]:
train_dir = r'C:\Users\Iver_Home\CP_ft\new_test'

In [85]:
def labeling(img):
    class_name = img.split('.')[0]
    if class_name == 'dunhill':
        return 0
    elif class_name =='marlboro':
        return 2
    elif class_name =='esse':
        return 3
    elif class_name =='bohem':
        return 4
    elif class_name =='mevius':
        return 1
    

In [86]:
print(labeling('esse.14.jpg'))

3


In [87]:
print(os.listdir(train_dir))

['bohem.1.jpg', 'bohem.2.jpg', 'bohem.3.jpg', 'bohem.4.jpg', 'bohem.5.jpg', 'dunhill.1.jpg', 'dunhill.2.jpg', 'dunhill.3.jpg', 'dunhill.4.jpg', 'dunhill.5.jpg', 'esse.1.jpg', 'esse.2.jpg', 'esse.3.jpg', 'esse.4.jpg', 'esse.5.jpg', 'marlboro.1.jpg', 'marlboro.2.jpg', 'marlboro.3.jpg', 'marlboro.4.jpg', 'marlboro.5.jpg', 'mevius.1.jpg', 'mevius.2.jpg', 'mevius.3.jpg', 'mevius.4.jpg', 'mevius.5.jpg']


In [88]:
x_data = list()
t_data = list()

In [89]:

for img in tqdm(os.listdir(train_dir)):
    total = len(os.listdir(train_dir))   #=100
    #position = 0
    #leave = True
    label_data = labeling(img)
    img_path = os.path.join(train_dir,img)
    img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_COLOR),(126,95))
    #img_data : 3d array
    x_data.append(img_data.flatten())
    t_data.append(label_data)
print(img_data)
#print(x_data)

  0%|          | 0/25 [00:00<?, ?it/s]

[[[43 47 48]
  [43 47 48]
  [44 47 50]
  ...
  [36 39 43]
  [34 37 41]
  [36 39 43]]

 [[44 47 51]
  [44 48 49]
  [46 50 51]
  ...
  [35 38 42]
  [36 38 42]
  [36 38 42]]

 [[45 49 50]
  [42 46 47]
  [42 46 47]
  ...
  [36 39 43]
  [34 37 41]
  [37 39 44]]

 ...

 [[82 77 74]
  [77 73 70]
  [76 71 68]
  ...
  [32 30 29]
  [32 31 30]
  [35 31 30]]

 [[76 71 68]
  [79 74 71]
  [73 68 65]
  ...
  [32 30 29]
  [34 28 29]
  [35 31 30]]

 [[76 71 68]
  [76 71 68]
  [77 72 69]
  ...
  [35 31 30]
  [34 30 30]
  [35 30 29]]]


In [90]:
#  -126~126 --> 0~255
#arr128 = np.full((250,35910),128)
#x_data = x_data + arr128

x_data = np.array(x_data)
x_data = x_data + 128

x_df = pd.DataFrame(x_data)
t_df = pd.DataFrame({'label':t_data})
display(x_df)

0      1      2      3      4      5      6      7      8      9      ...  \
0     206    212    211    202    208    207    203    209    208    204  ...   
1     210    214    216    210    214    215    212    216    216    214  ...   
2     219    221    221    219    221    221    220    222    222    224  ...   
3     200    204    205    202    206    207    201    205    206    202  ...   
4     202    206    207    203    207    208    205    209    210    207  ...   
5     212    214    214    208    210    210    209    211    211    212  ...   
6     206    208    208    201    203    203    207    209    209    210  ...   
7     214    216    216    210    212    212    209    211    211    210  ...   
8     211    213    213    210    212    212    210    212    212    212  ...   
9     206    211    210    206    211    210    205    210    209    206  ...   
10    242    244    245    237    239    241    237    239    240    235  ...   
11    232    235    237    235    239    240    233    237    238    240  ...   
12    231    236    239    234    239    242    235    240    243    245  ...   
13    236    239    243    236    239    243    241    247    248    238  ...   
14    232    237    240    238    243    246    240    245    248    240  ...   
15    185    190    189    183    188    187    186    191    190    185  ...   
16    187    190    188    187    190    188    190    193    191    187  ...   
17    179    184    179    183    187    183    182    186    181    178  ...   
18    192    193    191    189    190    188    188    189    187    190  ...   
19    185    188    186    188    191    189    183    186    184    186  ...   
20    171    172    176    171    172    176    171    172    176    173  ...   
21    175    178    182    178    180    184    175    178    182    176  ...   
22    174    175    179    174    175    179    171    172    176    175  ...   
23    180    183    187    175    178    182    181    184    188    174  ...   
24    171    175    176    171    175    176    172    175    178    172  ...   

    35900  35901  35902  35903  35904  35905  35906  35907  35908  35909  
0     203    207    203    202    211    207    206    209    206    202  
1     175    177    175    174    177    175    173    177    175    174  
2     187    190    186    185    190    186    185    191    187    186  
3     178    183    179    178    183    179    178    182    178    177  
4     187    193    189    188    196    192    191    189    185    184  
5     224    244    237    233    245    238    234    233    226    223  
6     219    228    224    219    223    219    214    223    219    214  
7     213    216    212    208    216    213    208    220    217    213  
8     213    227    221    215    231    225    220    221    215    210  
9     202    210    207    201    205    201    196    200    195    191  
10    217    219    221    218    223    224    223    228    229    227  
11    211    213    211    210    214    215    213    217    215    214  
12    186    186    187    185    185    186    184    185    186    184  
13    204    208    206    205    209    207    206    213    211    210  
14    206    207    205    205    205    203    202    202    201    199  
15    160    158    161    159    159    164    162    161    166    164  
16    165    167    172    170    164    170    168    164    167    166  
17    163    166    170    165    170    172    168    169    170    166  
18    171    167    172    171    168    173    171    165    170    168  
19    165    161    166    164    158    163    161    159    164    162  
20    168    177    172    169    177    172    169    172    169    165  
21    190    198    190    187    207    200    197    211    204    201  
22    169    178    173    170    173    170    166    180    177    173  
23    176    180    177    173    185    182    178    183    178    175  
24    157    163    15

In [91]:
df = pd.merge(t_df, x_df, left_index=True, right_index=True)
display(df)

label    0    1    2    3    4    5    6    7    8  ...  35900  35901  \
0       4  206  212  211  202  208  207  203  209  208  ...    203    207   
1       4  210  214  216  210  214  215  212  216  216  ...    175    177   
2       4  219  221  221  219  221  221  220  222  222  ...    187    190   
3       4  200  204  205  202  206  207  201  205  206  ...    178    183   
4       4  202  206  207  203  207  208  205  209  210  ...    187    193   
5       0  212  214  214  208  210  210  209  211  211  ...    224    244   
6       0  206  208  208  201  203  203  207  209  209  ...    219    228   
7       0  214  216  216  210  212  212  209  211  211  ...    213    216   
8       0  211  213  213  210  212  212  210  212  212  ...    213    227   
9       0  206  211  210  206  211  210  205  210  209  ...    202    210   
10      3  242  244  245  237  239  241  237  239  240  ...    217    219   
11      3  232  235  237  235  239  240  233  237  238  ...    211    213   
12      3  231  236  239  234  239  242  235  240  243  ...    186    186   
13      3  236  239  243  236  239  243  241  247  248  ...    204    208   
14      3  232  237  240  238  243  246  240  245  248  ...    206    207   
15      2  185  190  189  183  188  187  186  191  190  ...    160    158   
16      2  187  190  188  187  190  188  190  193  191  ...    165    167   
17      2  179  184  179  183  187  183  182  186  181  ...    163    166   
18      2  192  193  191  189  190  188  188  189  187  ...    171    167   
19      2  185  188  186  188  191  189  183  186  184  ...    165    161   
20      1  171  172  176  171  172  176  171  172  176  ...    168    177   
21      1  175  178  182  178  180  184  175  178  182  ...    190    198   
22      1  174  175  179  174  175  179  171  172  176  ...    169    178   
23      1  180  183  187  175  178  182  181  184  188  ...    176    180   
24      1  171  175  176  171  175  176  172  175  178  ...    157    163   

    35902  35903  35904  35905  35906  35907  35908  35909  
0     203    202    211    207    206    209    206    202  
1     175    174    177    175    173    177    175    174  
2     186    185    190    186    185    191    187    186  
3     179    178    183    179    178    182    178    177  
4     189    188    196    192    191    189    185    184  
5     237    233    245    238    234    233    226    223  
6     224    219    223    219    214    223    219    214  
7     212    208    216    213    208    220    217    213  
8     221    215    231    225    220    221    215    210  
9     207    201    205    201    196    200    195    191  
10    221    218    223    224    223    228    229    227  
11    211    210    214    215    213    217    215    214  
12    187    185    185    186    184    185    186    184  
13    206    205    209    207    206    213    211    210  
14    205    205    205    203    202    202    201    199  
15    161    159    159    164    162    161    166    164  
16    172    170    164    170    168    164    167    166  
17    170    165    170    172    168    169    170    166  
18    172    171    168    173    171    165    170    168  
19    166    164    158    163    161    159    164    162  
20    172    169    177    172    169    172    169    165  
21    190    187    207    200    197    211    204    201  
22    173    170    173    170    166    180    177    173  
23    177    173    185    182    178    183    178    175  
24    159    158    162    158    158    163    158    157  

[25 rows x 35911 columns]

In [92]:
shuffled_df = utils.shuffle(df)

In [93]:
shuffled_df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\color_test_newimg_trial2_20220529.csv', index=False)
#df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test_all2.csv', index=False)