In [1]:
import numpy as np
import cv2
import pandas as pd

In [2]:
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\mevius.1.jpg')
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\mevius.1.jpg',1)
img1 = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mevius\mevius.1.jpg',cv2.IMREAD_COLOR)
img1 = cv2.resize(img1,(504,378))

print(type(img1))

cv2.imshow("image1",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>


In [ ]:
img1_grey = cv2.imread(r'C:\Users\Iver_Home\CP_ft\mix\bohem.14.jpg',cv2.IMREAD_GRAYSCALE)
img1_grey = cv2.resize(img1_grey,(504,378))

cv2.imshow("image1_grey",img1_grey)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
print(type(img1_grey))
print(img1_grey)
np.savetxt('ttest.csv',img1_grey,delimiter=",")

<class 'numpy.ndarray'>
[[35 43 45 ... 44 40 41]
 [37 45 39 ... 35 40 40]
 [42 39 39 ... 45 38 42]
 ...
 [41 42 41 ... 24 27 25]
 [35 39 46 ... 35 24 29]
 [20 38 39 ... 29 26 25]]


In [ ]:
df = pd.DataFrame(img1_grey)

df.to_csv('tttest.csv', index=False)

In [ ]:
canny_img1 = cv2.Canny(img1_grey, 100,255)

cv2.imshow("canny",canny_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
sobel_img1 = cv2.Sobel(img1_grey, cv2.CV_8U, 1, 0, 3)

cv2.imshow("sobel", sobel_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
laplacian_img1 = cv2.Laplacian(img1_grey, cv2.CV_8U, ksize=3)

cv2.imshow("laplacian", laplacian_img1)
cv2.waitKey()
cv2.destroyAllWindows()