In [12]:
import cv2
import numpy as np
import pandas as pd
import os
from sklearn import utils
from tqdm.notebook import tqdm

In [13]:
train_dir = r'C:\Users\Iver_Home\CP_ft\mix'

In [14]:
def labeling(img):
    class_name = img.split('.')[0]
    if class_name == 'mevius':
        return 1
    elif class_name =='marlboro':
        return 2
    elif class_name =='esse':
        return 3
    elif class_name =='bohem':
        return 4
    elif class_name =='dunhill':
        return 0
    

In [15]:
print(labeling('dunhill.14.jpg'))

0


In [16]:
x_data = list()
t_data = list()

In [17]:
print(os.listdir(train_dir))
arr127 = np.full((252,189),127)



['bohem.1.jpg', 'bohem.10.jpg', 'bohem.11.jpg', 'bohem.12.jpg', 'bohem.13.jpg', 'bohem.14.jpg', 'bohem.15.jpg', 'bohem.16.jpg', 'bohem.17.jpg', 'bohem.18.jpg', 'bohem.19.jpg', 'bohem.2.jpg', 'bohem.20.jpg', 'bohem.3.jpg', 'bohem.4.jpg', 'bohem.5.jpg', 'bohem.6.jpg', 'bohem.7.jpg', 'bohem.8.jpg', 'bohem.9.jpg', 'dunhill.1.jpg', 'dunhill.10.jpg', 'dunhill.11.jpg', 'dunhill.12.jpg', 'dunhill.13.jpg', 'dunhill.14.jpg', 'dunhill.15.jpg', 'dunhill.16.jpg', 'dunhill.17.jpg', 'dunhill.18.jpg', 'dunhill.19.jpg', 'dunhill.2.jpg', 'dunhill.20.jpg', 'dunhill.3.jpg', 'dunhill.4.jpg', 'dunhill.5.jpg', 'dunhill.6.jpg', 'dunhill.7.jpg', 'dunhill.8.jpg', 'dunhill.9.jpg', 'esse.1.jpg', 'esse.10.jpg', 'esse.11.jpg', 'esse.12.jpg', 'esse.13.jpg', 'esse.14.jpg', 'esse.15.jpg', 'esse.16.jpg', 'esse.17.jpg', 'esse.18.jpg', 'esse.19.jpg', 'esse.2.jpg', 'esse.20.jpg', 'esse.3.jpg', 'esse.4.jpg', 'esse.5.jpg', 'esse.6.jpg', 'esse.7.jpg', 'esse.8.jpg', 'esse.9.jpg', 'marlboro.1.jpg', 'marlboro.10.jpg', 'marlboro

In [18]:

for img in tqdm(os.listdir(train_dir)):
    total = len(os.listdir(train_dir))   #=100
    position = 0
    leave = True
    label_data = labeling(img)
    img_path = os.path.join(train_dir,img)
    img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_GRAYSCALE),(189,252))
    #img_data : 2d array
    img_data = img_data + arr127
    x_data.append(img_data.ravel())
    t_data.append(label_data)
print(img_data)

  0%|          | 0/100 [00:00<?, ?it/s]

[[156 143 177 ... 154 163 158]
 [147 157 152 ... 175 175 152]
 [156 162 157 ... 180 166 166]
 ...
 [161 167 160 ... 151 143 141]
 [164 149 143 ... 153 157 150]
 [164 161 159 ... 142 142 143]]


In [19]:
x_df = pd.DataFrame(x_data)
t_df = pd.DataFrame({'label':t_data})
display(x_df)

0      1      2      3      4      5      6      7      8      9      ...  \
0     175    179    190    195    178    181    184    191    183    188  ...   
1     174    177    166    169    168    171    173    175    177    170  ...   
2     170    174    177    176    181    179    175    179    177    179  ...   
3     186    177    189    184    176    180    178    174    182    180  ...   
4     172    186    181    183    179    176    182    175    177    175  ...   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
95    162    162    167    173    167    167    170    169    168    170  ...   
96    176    178    168    170    170    173    175    171    177    182  ...   
97    183    188    188    175    170    171    168    168    164    167  ...   
98    161    169    167    169    175    185    172    184    188    181  ...   
99    156    143    177    151    149    156    158    157    165    167  ...   

    47618  47619  47620  47621  47622  47623  47624  47625  47626  47627  
0     173    167    169    172    169    174    167    171    175    179  
1     170    171    172    175    177    178    173    186    169    169  
2     169    177    179    176    173    186    188    175    179    182  
3     184    184    179    171    185    183    171    184    179    176  
4     182    183    184    178    182    191    180    182    192    183  
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
95    156    158    158    160    166    166    160    163    166    156  
96    159    154    162    157    160    152    163    166    171    159  
97    157    152    149    156    156    157    146    154    153    148  
98    153    156    157    165    156    156    155    163    160    151  
99    149    148    147    154    138    152    143    142    142    143  

[100 rows x 47628 columns]

In [20]:
df = pd.merge(t_df, x_df, left_index=True, right_index=True)
display(x_df)

0      1      2      3      4      5      6      7      8      9      ...  \
0     175    179    190    195    178    181    184    191    183    188  ...   
1     174    177    166    169    168    171    173    175    177    170  ...   
2     170    174    177    176    181    179    175    179    177    179  ...   
3     186    177    189    184    176    180    178    174    182    180  ...   
4     172    186    181    183    179    176    182    175    177    175  ...   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
95    162    162    167    173    167    167    170    169    168    170  ...   
96    176    178    168    170    170    173    175    171    177    182  ...   
97    183    188    188    175    170    171    168    168    164    167  ...   
98    161    169    167    169    175    185    172    184    188    181  ...   
99    156    143    177    151    149    156    158    157    165    167  ...   

    47618  47619  47620  47621  47622  47623  47624  47625  47626  47627  
0     173    167    169    172    169    174    167    171    175    179  
1     170    171    172    175    177    178    173    186    169    169  
2     169    177    179    176    173    186    188    175    179    182  
3     184    184    179    171    185    183    171    184    179    176  
4     182    183    184    178    182    191    180    182    192    183  
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
95    156    158    158    160    166    166    160    163    166    156  
96    159    154    162    157    160    152    163    166    171    159  
97    157    152    149    156    156    157    146    154    153    148  
98    153    156    157    165    156    156    155    163    160    151  
99    149    148    147    154    138    152    143    142    142    143  

[100 rows x 47628 columns]

In [21]:
shuffled_df = utils.shuffle(df)

In [22]:
shuffled_df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\train_100_20220522.csv', index=False)
#df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test_all2.csv', index=False)