In [21]:
import cv2
import numpy as np
import pandas as pd
import os
from sklearn import utils
from tqdm.notebook import tqdm

In [22]:
train_dir = r'C:\Users\Iver_Home\CP_ft\temp'

In [23]:
def labeling(img):
    class_name = img.split('.')[0]
    if class_name == 'mevius':
        return 1
    elif class_name =='marlboro':
        return 2
    elif class_name =='esse':
        return 3
    elif class_name =='bohem':
        return 4
    elif class_name =='dunhill':
        return 5
    

In [24]:
print(labeling('esse.14.jpg'))

3


In [25]:
x_data = list()
t_data = list()

In [26]:
print(os.listdir(train_dir))

for img in tqdm(os.listdir(train_dir)):
    total = len(os.listdir(train_dir))   #=100
    position = 0
    leave = True
    label_data = labeling(img)
    img_path = os.path.join(train_dir,img)
    img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_COLOR),(189,252))
    #img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_GRAYSCALE),(189,252))
    #img_data : 3d array
    x_data.append(img_data.ravel())
    t_data.append(label_data)

['bohem.14.jpg']


  0%|          | 0/1 [00:00<?, ?it/s]

In [31]:
print(img_data)

[[[222 220 219]
  [215 213 212]
  [206 206 200]
  ...
  [ 57  59  47]
  [ 56  58  48]
  [ 50  54  42]]

 [[216 214 213]
  [211 210 206]
  [174 179 170]
  ...
  [ 61  63  51]
  [ 56  58  46]
  [ 56  58  46]]

 [[212 210 209]
  [195 199 190]
  [147 157 144]
  ...
  [ 62  61  51]
  [ 65  67  55]
  [ 64  66  54]]

 ...

 [[ 11  18  11]
  [ 28  35  29]
  [ 31  38  31]
  ...
  [ 31  35  30]
  [ 34  38  33]
  [ 26  30  25]]

 [[ 25  32  25]
  [ 33  40  34]
  [ 35  42  35]
  ...
  [ 30  34  29]
  [ 32  36  31]
  [ 30  34  29]]

 [[ 26  31  22]
  [ 25  32  25]
  [ 36  44  37]
  ...
  [ 34  38  32]
  [ 33  37  32]
  [ 31  35  29]]]


In [27]:
x_df = pd.DataFrame(x_data)
t_df = pd.DataFrame({'label':t_data})
display(x_df)

0       1       2       3       4       5       6       7       8       \
0     -34     -36     -37     -41     -43     -44     -50     -50     -56   

   9       ...  142874  142875  142876  142877  142878  142879  142880  \
0     -86  ...      31      34      38      32      33      37      32   

   142881  142882  142883  
0      31      35      29  

[1 rows x 142884 columns]

In [28]:
df = pd.merge(t_df, x_df, left_index=True, right_index=True)
display(x_df)

0       1       2       3       4       5       6       7       8       \
0     -34     -36     -37     -41     -43     -44     -50     -50     -56   

   9       ...  142874  142875  142876  142877  142878  142879  142880  \
0     -86  ...      31      34      38      32      33      37      32   

   142881  142882  142883  
0      31      35      29  

[1 rows x 142884 columns]

In [29]:
#shuffled_df = utils.shuffle(df)

In [30]:
#shuffled_df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test.csv', index=False)
df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test3.csv', index=False)