In [12]:
import cv2
import numpy as np
import pandas as pd
import os
from sklearn import utils
from tqdm.notebook import tqdm

In [13]:
train_dir = r'C:\Users\Iver_Home\CP_ft\temp'

In [14]:
def labeling(img):
    class_name = img.split('.')[0]
    if class_name == 'mevius':
        return 0
    elif class_name =='marlboro':
        return 1
    elif class_name =='esse':
        return 2
    elif class_name =='bohem':
        return 3
    elif class_name =='dunhill':
        return 4
    

In [15]:
print(labeling('esse.14.jpg'))

2


In [16]:
x_data = list()
t_data = list()

In [17]:
print(os.listdir(train_dir))

for img in tqdm(os.listdir(train_dir)):
    total = len(os.listdir(train_dir))   #=100
    label_data = labeling(img)
    img_path = os.path.join(train_dir,img)
    img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_GRAYSCALE),(252,189))
    #img_data : 2d array
    x_data.append(img_data.ravel())
    t_data.append(label_data)
print(img_data)
    


['bohem.14.jpg']


  0%|          | 0/1 [00:00<?, ?it/s]

[[218 215 207 ...  62  49  55]
 [216 209 192 ...  63  55  63]
 [206 178 156 ...  60  57  53]
 ...
 [ 29  29  29 ...  33  33  36]
 [ 28  32  32 ...  36  32  37]
 [ 28  29  27 ...  34  31  33]]


In [18]:

print(img_data.shape)

# Or use the `len()` function with the `index` property
print(len(df.index))


(189, 252)
1


In [19]:
x_df = pd.DataFrame(x_data)
t_df = pd.DataFrame({'label':t_data})
display(x_df)

0      1      2      3      4      5      6      7      8      9      ...  \
0    -38    -41    -49    -57    -82   -110   -115    -91    -70    -67  ...   

   47618  47619  47620  47621  47622  47623  47624  47625  47626  47627  
0     31     38     37     31     36     34     33     34     31     33  

[1 rows x 47628 columns]

In [20]:
df = pd.merge(t_df, x_df, left_index=True, right_index=True)
display(x_df)

0      1      2      3      4      5      6      7      8      9      ...  \
0    -38    -41    -49    -57    -82   -110   -115    -91    -70    -67  ...   

   47618  47619  47620  47621  47622  47623  47624  47625  47626  47627  
0     31     38     37     31     36     34     33     34     31     33  

[1 rows x 47628 columns]

In [21]:
#shuffled_df = utils.shuffle(df)

In [22]:
#shuffled_df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test.csv', index=False)
df.to_csv(r'C:\Users\Iver_Home\CP_ft\mix_output\test3.csv', index=False)