In [10]:
import cv2
import numpy as np
import pandas as pd
import os
from sklearn import utils
from tqdm.notebook import tqdm

In [11]:
train_dir = r'C:\Users\Iver_Home\CP_ft\new_train'

In [12]:
def labeling(img):
    class_name = img.split('.')[0]
    if class_name == 'bohem':
        return 0
    elif class_name =='dunhill':
        return 1
    elif class_name =='esse':
        return 2
    elif class_name =='marlboro':
        return 3
    elif class_name =='mevius':
        return 4
    

In [13]:
raw_data = np.zeros((83625))      # pixel size (*3 if color)
label_data = np.zeros((1))

#raw_data = np.array(list())
#label_data = np.array(list())

label_data

array([0.])

In [14]:
for img_file in tqdm(os.listdir(train_dir)):
   
    img_path = os.path.join(train_dir,img_file)
    img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_COLOR),(223,125))
    flat_img_data = np.ravel(img_data,order='C')
    
    label = np.array([labeling(img_file)])
    
    raw_data = np.append(raw_data, flat_img_data, axis=0)
    label_data = np.append(label_data, label, axis=0)

img_amount = len(os.listdir(train_dir))

raw_data = np.reshape(raw_data,(img_amount+1,83625))
label_data = np.reshape(label_data,(img_amount+1,1))

print(raw_data)
print(label_data)

  0%|          | 0/250 [00:00<?, ?it/s]

[[ 0.  0.  0. ...  0.  0.  0.]
 [77. 83. 82. ... 82. 79. 75.]
 [89. 94. 93. ... 60. 58. 56.]
 ...
 [40. 42. 42. ... 42. 38. 37.]
 [56. 55. 57. ... 54. 48. 43.]
 [40. 44. 45. ... 41. 38. 35.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.

In [15]:
combined_data = np.concatenate((label_data, raw_data), axis=1)
print(combined_data)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0. 77. 83. ... 82. 79. 75.]
 [ 0. 89. 94. ... 60. 58. 56.]
 ...
 [ 4. 40. 42. ... 42. 38. 37.]
 [ 4. 56. 55. ... 54. 48. 43.]
 [ 4. 40. 44. ... 41. 38. 35.]]


In [16]:
semi_final_outputs = combined_data[1:img_amount+1]
print(semi_final_outputs)

[[  0.  77.  83. ...  82.  79.  75.]
 [  0.  89.  94. ...  60.  58.  56.]
 [  0.  98. 100. ...  98.  94.  93.]
 ...
 [  4.  40.  42. ...  42.  38.  37.]
 [  4.  56.  55. ...  54.  48.  43.]
 [  4.  40.  44. ...  41.  38.  35.]]


In [17]:
final_outputs = np.random.permutation(semi_final_outputs)
print(final_outputs)

[[  4.  40.  44. ...  41.  38.  35.]
 [  0.  93.  95. ...  56.  52.  51.]
 [  2. 103. 107. ...  92.  91.  90.]
 ...
 [  3.  53.  56. ...  56.  58.  52.]
 [  2.  87.  94. ...  72.  73.  71.]
 [  1.  83.  80. ...  54.  58.  53.]]


In [18]:
np.savetxt('train_250_20220531.csv',final_outputs,fmt='%d',delimiter=",")