In [1]:
import cv2
import numpy as np
import pandas as pd
import os
from sklearn import utils
from tqdm.notebook import tqdm

In [2]:
train_dir = r'C:\Users\Iver_Home\CP_ft\temp'

In [3]:
def labeling(img):
    class_name = img.split('.')[0]
    if class_name == 'bohem':
        return 0
    elif class_name =='dunhill':
        return 1
    elif class_name =='esse':
        return 2
    elif class_name =='marlboro':
        return 3
    elif class_name =='mevius':
        return 4
    

In [4]:
print(labeling('esse.14.jpg'))

2


In [5]:
raw_data = np.zeros((83625),int)      # pixel size (*3 if color)
label_data = np.zeros((1),int)

raw_data

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
for img_file in tqdm(os.listdir(train_dir)):
   
    img_path = os.path.join(train_dir,img_file)
    img_data = cv2.resize(cv2.imread(img_path,cv2.IMREAD_COLOR),(223,125))
    flat_img_data = np.ravel(img_data,order='C')
    
    label = np.array([labeling(img_file)])
    
    raw_data = np.append(raw_data, flat_img_data, axis=0)
    label_data = np.append(label_data, label, axis=0)

img_amount = len(os.listdir(train_dir))

raw_data = np.reshape(raw_data,(img_amount+1,83625))
label_data = np.reshape(label_data,(img_amount+1,1))

print(raw_data)
print(label_data)

  0%|          | 0/1 [00:00<?, ?it/s]

[[  0   0   0 ...   0   0   0]
 [121 127 126 ... 114 117 115]]
[[0]
 [2]]


In [7]:
combined_data = np.concatenate((label_data, raw_data), axis=1)
print(combined_data)

[[  0   0   0 ...   0   0   0]
 [  2 121 127 ... 114 117 115]]


In [8]:
semi_final_outputs = combined_data[1:img_amount+1]
print(semi_final_outputs)

[[  2 121 127 ... 114 117 115]]


In [9]:
final_outputs = np.random.permutation(semi_final_outputs)

final_outputs = final_outputs.astype(int)

print(final_outputs)

[[  2 121 127 ... 114 117 115]]


In [10]:
np.savetxt('temp_20220531.csv',final_outputs,fmt='%d',delimiter=",")